export const intToRomanTestCases = [
  { num: 3749, expectedOutput: 'MMMDCCXLIX' },
  { num: 58, expectedOutput: 'LVIII' },
  { num: 1994, expectedOutput: 'MCMXCIV' },
  { num: 0, expectedOutput: '' },
  { num: 1, expectedOutput: 'I' },
  { num: 5, expectedOutput: 'V' },
  { num: 10, expectedOutput: 'X' },
  { num: 50, expectedOutput: 'L' },
  { num: 100, expectedOutput: 'C' },
  { num: 500, expectedOutput: 'D' },
  { num: 1000, expectedOutput: 'M' },
  { num: 4, expectedOutput: 'IV' },
  { num: 9, expectedOutput: 'IX' },
  { num: 40, expectedOutput: 'XL' },
  { num: 90, expectedOutput: 'XC' },
  { num: 400, expectedOutput: 'CD' },
  { num: 900, expectedOutput: 'CM' },
  { num: 3, expectedOutput: 'III' },
  { num: 8, expectedOutput: 'VIII' },
  { num: 13, expectedOutput: 'XIII' },
  { num: 38, expectedOutput: 'XXXVIII' },
  { num: 88, expectedOutput: 'LXXXVIII' },
  { num: 808, expectedOutput: 'DCCCVIII' },
  { num: 888, expectedOutput: 'DCCCLXXXVIII' },
  { num: 14, expectedOutput: 'XIV' },
  { num: 19, expectedOutput: 'XIX' },
  { num: 49, expectedOutput: 'XLIX' },
  { num: 409, expectedOutput: 'CDIX' },
  { num: 999, expectedOutput: 'CMXCIX' },
  { num: 3999, expectedOutput: 'MMMCMXCIX' },
]as {
  num: number;
  expectedOutput: string;
}[];
